services:
  - type: web
    name: biwoorld-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot_run.py"
    plan: free
    region: singapore
    envVars:
      - key: DISCORD_TOKEN
        sync: false
